#ifndef XSENS_XSENS_CONFIG_H_
#define XSENS_XSENS_CONFIG_H_

#include "stm32l4xx_hal.h"

#define XSENS_PIN_SET			(GPIO_PIN_SET)
#define XSENS_PIN_RESET			(GPIO_PIN_RESET)

#define XSENS_ENABLE			(1)
#define XSENS_DISABLE			(0)


#define XSENS_TIMOUT_100MS		(100)
#define XSENS_TIMOUT_10000MS	(10000)

/*
 *  SPI configuration
 */

#define XSENS_CS_PORT			(GPIOC)
#define XSENS_CS_PIN			(GPIO_PIN_4)

extern SPI_HandleTypeDef hspi1;
#define XSENS_SPI_HANDLER (&hspi1)

/*
 * Xsens Mti-1 configuration
 */

#define XSENS_CFG_TEMPERATURE			XSENS_DISABLE
#define XSENS_CFG_UTC_TIME				XSENS_DISABLE
#define XSENS_CFG_PACKET_COUNTER		XSENS_DISABLE
#define XSENS_CFG_SAMPLE_TIME_FINE		XSENS_DISABLE
#define XSENS_CFG_SAMPLE_TIME_COARSE	XSENS_DISABLE
#define XSENS_CFG_DELTA_V				XSENS_DISABLE
#define XSENS_CFG_ACCELERATION			XSENS_ENABLE
#define XSENS_CFG_ACCELERATION_HR		XSENS_DISABLE
#define XSENS_CFG_RATE_OF_TURN			XSENS_ENABLE
#define XSENS_CFG_DELTA_Q				XSENS_DISABLE
#define XSENS_CFG_RATE_OF_TURN_HR		XSENS_DISABLE
#define XSENS_CFG_MAGNETIC_FIELD		XSENS_ENABLE
#define XSENS_CFG_STATUS_BYTE			XSENS_DISABLE
#define XSENS_CFG_STATUS_WORD			XSENS_DISABLE







#endif /* XSENS_XSENS_CONFIG_H_ */
